# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Home
      title: This is the first menu item.
      path: homepage
      class: first
    - label: Page 1
      path: page/1
      submenu:
          - label: Page 2
            path: page/2
          - label: Page 3
            path: page/3
          - label: Page 4
            path: page/4
          - label: Page 5
            path: page/5
    - label: All pages
      path: pages
    - label: The Bolt site
      link: https://bolt.cm
      class: last
